### PR TITLE
[BACKLOG-35782] Handle the case where the bundleContext is invalid

### PR DESCRIPTION
**Pull request by andreramos89**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by andreramos89** [comment]
@smmribeiro 
@renato-s 
@bcostahitachivantara

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]

**Pull request merged**
