### PR TITLE
[BACKLOG-6861] - Making KarafLifecycleListener wait configurable, def…

### PR DESCRIPTION
**Pull request by brosander**
…ault to 100 seconds

### CODE REVIEW

**Comment by pentaho-nbaker** [comment]
End time is computed based on construction?

**Comment by brosander** [comment]
@pentaho-nbaker dumb mistake, was in the process of reviewing/wingmanning

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f core/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f core/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  core/src/main/java/org/pentaho/di/osgi/KarafLifecycleListener.java



License header violations:
==========================

1. core/src/main/java/org/pentaho/di/osgi/KarafLifecycleListener.java








Unit test coverage change:
============
org.pentaho.di.osgi.KarafLifecycleListener.new Runnable() {...}:
 * instructionPercentCoverageChange : +0.13%
    
org.pentaho.di.osgi.KarafLifecycleListener:
 * instructionPercentCoverageChange :**-11.42%**
 * branchPercentCoverageChange :**-8.33%**
 * linePercentCoverageChange :**-9.47%**
 * complexityPercentCoverageChange :**-6.29%**

**Comment by brosander** [comment]
will finish later

**Pull request merged**
