### PR TITLE
Backlog 6886

### PR DESCRIPTION
**Pull request by brosander**

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f core/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f core/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  core/src/main/java/org/pentaho/di/osgi/KarafLifecycleListener.java
  core/src/main/java/org/pentaho/di/osgi/OSGIPluginTracker.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/AggregatingNotifierListener.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifier.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifierListener.java
  core/src/test/java/org/pentaho/di/osgi/KarafLifecycleListenerTest.java
  core/src/test/java/org/pentaho/di/osgi/OSGIPluginTrackerTest.java
  core/src/test/java/org/pentaho/di/osgi/service/notifier/AggregatingNotifierListenerTest.java
  core/src/test/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifierTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File core/src/main/java/org/pentaho/di/osgi/OSGIPluginTracker.java
1. Message: ':' should be on a new line. at Line: 188 Column: 110
2. Message: '&&' should be on a new line. at Line: 190 Column: 63









Unit test coverage change:
============
org.pentaho.di.osgi.OSGIPluginTracker:
 * instructionPercentCoverageChange : +0.38%
 * linePercentCoverageChange : +0.44%
 * complexityPercentCoverageChange : +1.74%
    
org.pentaho.di.osgi.service.notifier.AggregatingNotifierListener:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.osgi.KarafLifecycleListener.2.new DelayedServiceNotifierListener() {...}:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.osgi.service.notifier.DelayedServiceNotifier:
 * instructionPercentCoverageChange :**-7.47%**
 * branchPercentCoverageChange :**-9.52%**
 * linePercentCoverageChange : +0.43%
 * complexityPercentCoverageChange :**-6.67%**
    
org.pentaho.di.osgi.KarafLifecycleListener:
 * instructionPercentCoverageChange : +0.69%
 * linePercentCoverageChange : +0.87%
 * complexityPercentCoverageChange : +1.10%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f core/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f core/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  core/src/main/java/org/pentaho/di/osgi/KarafLifecycleListener.java
  core/src/main/java/org/pentaho/di/osgi/OSGIPluginTracker.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/AggregatingNotifierListener.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifier.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifierListener.java
  core/src/test/java/org/pentaho/di/osgi/KarafLifecycleListenerTest.java
  core/src/test/java/org/pentaho/di/osgi/OSGIPluginTrackerTest.java
  core/src/test/java/org/pentaho/di/osgi/service/notifier/AggregatingNotifierListenerTest.java
  core/src/test/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifierTest.java










Unit test coverage change:
============
org.pentaho.di.osgi.OSGIPluginTracker:
 * instructionPercentCoverageChange : +0.38%
 * linePercentCoverageChange : +0.44%
 * complexityPercentCoverageChange : +1.74%
    
org.pentaho.di.osgi.service.notifier.AggregatingNotifierListener:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.osgi.KarafLifecycleListener.2.new DelayedServiceNotifierListener() {...}:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.osgi.service.notifier.DelayedServiceNotifier:
 * instructionPercentCoverageChange :**-7.47%**
 * branchPercentCoverageChange :**-9.52%**
 * linePercentCoverageChange : +0.43%
 * complexityPercentCoverageChange :**-6.67%**
    
org.pentaho.di.osgi.KarafLifecycleListener:
 * instructionPercentCoverageChange : +0.69%
 * linePercentCoverageChange : +0.87%
 * complexityPercentCoverageChange : +1.10%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f core/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f core/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  core/src/main/java/org/pentaho/di/osgi/KarafLifecycleListener.java
  core/src/main/java/org/pentaho/di/osgi/OSGIPluginTracker.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/AggregatingNotifierListener.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifier.java
  core/src/main/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifierListener.java
  core/src/test/java/org/pentaho/di/osgi/KarafLifecycleListenerTest.java
  core/src/test/java/org/pentaho/di/osgi/OSGIPluginTrackerTest.java
  core/src/test/java/org/pentaho/di/osgi/service/notifier/AggregatingNotifierListenerTest.java
  core/src/test/java/org/pentaho/di/osgi/service/notifier/DelayedServiceNotifierTest.java










Unit test coverage change:
============
org.pentaho.di.osgi.OSGIPluginTracker:
 * instructionPercentCoverageChange : +0.38%
 * linePercentCoverageChange : +0.44%
 * complexityPercentCoverageChange : +1.74%
    
org.pentaho.di.osgi.service.notifier.AggregatingNotifierListener:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.osgi.KarafLifecycleListener.2.new DelayedServiceNotifierListener() {...}:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.osgi.service.notifier.DelayedServiceNotifier:
 * instructionPercentCoverageChange :**-7.47%**
 * branchPercentCoverageChange :**-9.52%**
 * linePercentCoverageChange : +0.43%
 * complexityPercentCoverageChange :**-6.67%**
    
org.pentaho.di.osgi.KarafLifecycleListener:
 * instructionPercentCoverageChange : +0.69%
 * linePercentCoverageChange : +0.87%
 * complexityPercentCoverageChange : +1.10%

**Comment by brosander** [comment]
@pentaho-nbaker please review

**Pull request merged**
