### PR TITLE
[BACKLOG-35782] Handle the case where the bundleContext is invalid

### PR DESCRIPTION
**Pull request by andreramos89**

### CODE REVIEW

**Comment by andreramos89** [comment]
@smmribeiro 
@bcostahitachivantara 
@renato-s

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 20m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **142**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-osgi-bridge/job/PR-105/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Closing as it is no longer valid nor needed.

**Pull request closed without merging**
